//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefiKindom_QuestRunner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EncryptionKey {
            get {
                return ((string)(this["EncryptionKey"]));
            }
            set {
                this["EncryptionKey"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x5100bd31b822371108a0f63dcfb6594b9919eaf4")]
        public string QuestContractAddress {
            get {
                return ((string)(this["QuestContractAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x5f753dcdf9b1ad9aabc1346614d1f4746fd6ce5c")]
        public string HeroContractAddress {
            get {
                return ((string)(this["HeroContractAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x6391F796D56201D279a42fD3141aDa7e26A3B4A5")]
        public string ProfileContractAddress {
            get {
                return ((string)(this["ProfileContractAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x72cb10c6bfa5624dd07ef608027e366bd690048f")]
        public string JewelContractAddress {
            get {
                return ((string)(this["JewelContractAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x6ff019415ee105acf2ac52483a33f5b43eadb8d0")]
        public string MiningQuestContractAddress {
            get {
                return ((string)(this["MiningQuestContractAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0xE259e8386d38467f0E7fFEdB69c3c9C935dfaeFc")]
        public string FishingQuestContractAddress {
            get {
                return ((string)(this["FishingQuestContractAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x3132c76acF2217646fB8391918D28a16bD8A8Ef4")]
        public string ForagingQuestContractAddress {
            get {
                return ((string)(this["ForagingQuestContractAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x0548214A0760a897aF53656F4b69DbAD688D8f29")]
        public string WishingWellContractAddress {
            get {
                return ((string)(this["WishingWellContractAddress"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.harmony.one")]
        public string CurrentRpcUrl {
            get {
                return ((string)(this["CurrentRpcUrl"]));
            }
            set {
                this["CurrentRpcUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaterialBlueGrey")]
        public string AppTheme {
            get {
                return ((string)(this["AppTheme"]));
            }
            set {
                this["AppTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1666600000")]
        public string CurrentRpcShard {
            get {
                return ((string)(this["CurrentRpcShard"]));
            }
            set {
                this["CurrentRpcShard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MiningQuestTypeId {
            get {
                return ((int)(this["MiningQuestTypeId"]));
            }
            set {
                this["MiningQuestTypeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FishingQuestTypeId {
            get {
                return ((int)(this["FishingQuestTypeId"]));
            }
            set {
                this["FishingQuestTypeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ForagingQuestTypeId {
            get {
                return ((int)(this["ForagingQuestTypeId"]));
            }
            set {
                this["ForagingQuestTypeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WishingWellQuestTypeId {
            get {
                return ((int)(this["WishingWellQuestTypeId"]));
            }
            set {
                this["WishingWellQuestTypeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoStartQuestingOnStartup {
            get {
                return ((bool)(this["AutoStartQuestingOnStartup"]));
            }
            set {
                this["AutoStartQuestingOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastWalletIndex {
            get {
                return ((global::System.DateTime)(this["LastWalletIndex"]));
            }
            set {
                this["LastWalletIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstInit {
            get {
                return ((bool)(this["FirstInit"]));
            }
            set {
                this["FirstInit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int JewelInstanceMsInterval {
            get {
                return ((int)(this["JewelInstanceMsInterval"]));
            }
            set {
                this["JewelInstanceMsInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int QuestInstanceMsInterval {
            get {
                return ((int)(this["QuestInstanceMsInterval"]));
            }
            set {
                this["QuestInstanceMsInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeToTray {
            get {
                return ((bool)(this["MinimizeToTray"]));
            }
            set {
                this["MinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ec2-54-172-211-174.compute-1.amazonaws.com:9195/")]
        public string ExecutorApi {
            get {
                return ((string)(this["ExecutorApi"]));
            }
            set {
                this["ExecutorApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastKnownJewelHolder {
            get {
                return ((string)(this["LastKnownJewelHolder"]));
            }
            set {
                this["LastKnownJewelHolder"] = value;
            }
        }
    }
}
